### ISSUE TITLE
Missing test_qtdesigner.ui

### ISSUE THREAD

**Issue by JAMoreno-Larios** [PlotPyStack/plotpy#1]
Hello,

I tried to run the plotpy.tests.gui.run() module, but I found a FileNotFoundError. I installed plotpy from source.

Here's the error traceback:
```python
Traceback (most recent call last):
  File "/home/jose/big_data/hyperspectral_pufrfish/mcr_als_trilinear/run_test.py", line 14, in <module>
    run()
  File "/labadmin/mambaforge/envs/hyperspectral/lib/python3.11/site-packages/plotpy/tests/gui/__init__.py", line 19, in run
    run_testlauncher(plotpy)
  File "/labadmin/mambaforge/envs/hyperspectral/lib/python3.11/site-packages/guidata/guitest.py", line 349, in run_testlauncher
    win = TestLauncherWindow(package)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labadmin/mambaforge/envs/hyperspectral/lib/python3.11/site-packages/guidata/guitest.py", line 328, in __init__
    self.mainview = TestMainView(package, self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labadmin/mambaforge/envs/hyperspectral/lib/python3.11/site-packages/guidata/guitest.py", line 242, in __init__
    self.tests = get_tests(package, category="visible")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labadmin/mambaforge/envs/hyperspectral/lib/python3.11/site-packages/guidata/guitest.py", line 86, in get_tests
    test = TestModule(test_package, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labadmin/mambaforge/envs/hyperspectral/lib/python3.11/site-packages/guidata/guitest.py", line 114, in __init__
    _temp = __import__(subpkgname, fromlist=[module_name])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labadmin/mambaforge/envs/hyperspectral/lib/python3.11/site-packages/plotpy/tests/gui/test_qtdesigner.py", line 24, in <module>
    FormClass = loadui(os.path.splitext(__file__)[0] + ".ui")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labadmin/mambaforge/envs/hyperspectral/lib/python3.11/site-packages/plotpy/widgets/qtdesigner.py", line 39, in loadui
    uifile_text = open(fname).read().replace(replace_class, "QFrame")
                  ^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/labadmin/mambaforge/envs/hyperspectral/lib/python3.11/site-packages/plotpy/tests/gui/test_qtdesigner.ui'
```

Thank you for looking into this!

**Comment by PierreRaybaut** [comment]
Thanks for you feedback.

It should be fixed if you reinstall it from source.
Please do not hesitate to get back to me if it's still there.
